server:
  port: 0

spring:
  application:
    name: stock-data-aggregator-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${DISCOVERY_SERVICE_PORT}/eureka
  instance:
    instance-id: ${random.uuid}