server:
  port: ${API_GATEWAY_PORT}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test-service
          uri: lb://eureka-client-service
          predicates:
            - Path=/test/**
          filters:
            - AuthenticationFilter

        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/authentication/**

        - id: stock-data-aggregator-service
          uri: lb://stock-data-aggregator-service
          predicates:
            - Path=/quotation/**
          filters:
            - AuthenticationFilter


eureka:
  client:
    service-url:
      defaultZone: http://localhost:${DISCOVERY_SERVICE_PORT}/eureka

authentication:
  base-url: http://localhost:${API_GATEWAY_PORT}/authentication
  token-endpoint: /token
  validate-token-endpoint: /validate-token
  register-endpoint: /register